server:
  port: 8080
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bdd_java_exercice
    username: user
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver